### ISSUE TITLE
[ENH] sktime-pywatts integration - umbrella issue

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2653]
The `sktime` and `pywatts` packages have decided to explore integration, especially of the `keras`-like pipeline architecture that `pywatts` has.

This issue is an umbrella issue for that integration and collects work items.

- [ ] high-priority design item: https://github.com/alan-turing-institute/sktime/issues/2654
- [ ] high-priority design item: https://github.com/alan-turing-institute/sktime/issues/2655
- [ ] further design items
- [ ] design exploration:
   - [ ] current `sktime`/`pywatts` closest interface points for transformers: #2918
   - [ ] `sktime` simple `GraphPipeline` using `__call__` dunder: #2919
   - [ ] subsetting transform and `[]` dunder: #2907
- [ ] implementation (sub-items tbd)

Minutes of meetings and design sketches can be found here (file name YYYYMMDD-pywatts.md):
https://github.com/sktime/community-org/tree/main/meetups/previous_meetings

Project board:
https://github.com/alan-turing-institute/sktime/projects/30

**Comment by fkiraly** [comment]
FYI @benheid, @smeisen, @kalebphipps

**Comment by benHeid** [comment]
I think this umbrella issue can be closed, since the graphical pipeline is implemented.

Note, the implemented design is not needing the last open issue.
