### ISSUE TITLE
[ENH] Umbrella Issue -  Tracking the Deep Learning based estimator's tests Most tests are being skipped now

### ISSUE THREAD

**Issue by fnhirwa** [sktime/sktime#6826]
Most of the tests failing sporadically are of `TensorFlow` based estimators.

A deep dive into this issue was related to the `tf` latest version installed as a dependency(`v:2.16.2`)

Importing the tensorflow after pandas are imported seems to be the issue here as per this discussion [Importing pandas before tensorflow makes the script freeze](https://stackoverflow.com/questions/78561116/importing-pandas-before-tensorflow-makes-the-script-freeze).
When I tried to run the `estimator_check` from this PR: https://github.com/sktime/sktime/pull/6763 with the import of the tensorflow before calling the function the tests ran successfully.

```python
import tensorflow as tf

from sktime.classification.deep_learning.mcnn import MCNNClassifier
from sktime.utils.estimator_checks import check_estimator

check_estimator(MCNNClassifier)
```

This runs successfully locally with the version: `2.16.2`

The generalised workaround is to downgrade the `TensorFlow` version to `2.15.0` which seems to fix the need to import tensorflow before calling the `check_estimator` function.

This issue tracks all PRs and issues related to the failures of DL based estimators tests:

- [ ] https://github.com/sktime/sktime/issues/4610
- [ ] https://github.com/sktime/sktime/pull/6138
- [ ] https://github.com/sktime/sktime/pull/4702
- [ ] https://github.com/sktime/sktime/issues/6344

**Comment by fkiraly** [comment]
Well, that's an illuminating observation! I would have never thought.

Importing `pandas` before `tensorflow` causes freezes? How very very odd.

Reminds me of chemistry class:
["first pour the water, then the acid"](https://chemistry.stackexchange.com/questions/893/why-add-water-first-then-acid)

So, `pandas` is like acid. Sounds plausible.

**Comment by fkiraly** [comment]
waitasecond - how would this explain memory failures *before* 2.16 was released, in some of the issues?

That would mean there are, potentially, multiple issues at play?

**Comment by fnhirwa** [comment]
> waitasecond - how would this explain memory failures _before_ 2.16 was released (March 2024), in some of the issues (2023)?
> 
> That would mean there are, potentially, multiple issues at play?

Not quite sure about that but I recall at some point there was still the issue of tensorflow and torch not being compatible with other libraries at the import, mostly on machines with GPUs, related issues should be this https://github.com/pytorch/pytorch/issues/102360 and https://github.com/tensorflow/tensorflow/issues/60109

The version here was 2.12 and it was problematic 🙄
I will try with this version to confirm if this was a problem back then also.
